### ISSUE TITLE
<HOSTNAME_FROM_SERVICE>

### ISSUE THREAD

**Issue by zhaojc** [ibagroup-eu/Visual-Flow-deploy#2]
how can i get the actual value for HOSTNAME_FROM_SERVICE?thank you very much

**Comment by AGSadovsky** [comment]
Hello Zhao
Sorry for late response. This info is available in the installation guides (AWS, minikube branches), p.9.

<HOSTNAME_FROM_SERVICE> contains ip/hostname of your application.

For AWS installation you can get it using the next command:
`kubectl get svc vf-app-frontend -o yaml | grep hostname | cut -c 17-`

Use `minikube ip` command to get it for minikube.

Let us know if you have more questions.
